version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - my-network

  selenium:
    image: selenium/standalone-chrome:latest
    # image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    restart: always
    networks:
      - my-network

  my_app:
    build:
      context: ./script
      dockerfile: Dockerfile.script
    depends_on:
      - web
      - selenium
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./script:/app
    command: python3 -u main.py >> /app/output.log 2>&1
    restart: always
    networks:
      - my-network

networks:
  my-network:
